window.featuredProjects = [
  {
    id: 0,
    name: "ByondXR",
    thumbnail: "assets/images/spourmo-web.jpg",
    preview: "https://alsiam.github.io/web-projects/spourmo-web",
    code: "https://github.com/alsiam/web-projects/tree/main/spourmo-web",
  },

  {
    id: 1,
    name: "AI Shop Cart",
    thumbnail: "assets/images/shopping-cart.png",
    preview: "https://alsiam.github.io/web-projects/simple-cart",
    code: "https://github.com/alsiam/web-projects/tree/main/simple-cart",
  },
  
  {
    id: 2,
    name: "WayuMD",
    thumbnail: "assets/images/cuda-portfolio.jpg",
    preview: "https://alsiam.github.io/web-projects/cuda-portfolio",
    code: "https://github.com/alsiam/web-projects/tree/main/cuda-portfolio",
  },
  {
    id: 3,
    name: "Dream Theme",
    thumbnail: "assets/images/dream-theme.png",
    preview: "https://alsiam.github.io/web-projects/dream-theme",
    code: "https://github.com/alsiam/web-projects/tree/main/dream-theme",
  },
  {
    id: 4,
    name: "SRS Medicines-Ecommerce",
    thumbnail: "assets/images/SRS_Medicines.jpg",
    preview: "https://alsiam.github.io/web-projects/bike-palace",
    code: "https://github.com/alsiam/web-projects/tree/main/bike-palace",
  },
  {
    id: 5,
    name: "Simple Blog",
    thumbnail: "assets/images/simple-blog.png",
    preview: "https://alsiam.github.io/web-projects/simple-blog",
    code: "https://github.com/alsiam/web-projects/tree/main/simple-blog",
  },
];

window.totalProjects = [
  {
    id: 6,
    name: "Jamuna News",
    thumbnail: "assets/images/jamuna-news.png",
    preview: "https://alsiam.github.io/web-projects/jamuna-news",
    code: "https://github.com/alsiam/web-projects/tree/main/jamuna-news",
  },
  {
    id: 7,
    name: "Hamburger Food",
    thumbnail: "assets/images/hamburger-food.png",
    preview: "https://alsiam.github.io/web-projects/hamburger-food",
    code: "https://github.com/alsiam/web-projects/tree/main/hamburger-food",
  },
  {
    id: 8,
    name: "Interact",
    thumbnail: "assets/images/Interact.jpg",
    preview: "https://alsiam.github.io/web-projects/restaurant-menu",
    code: "https://github.com/alsiam/web-projects/tree/main/restaurant-menu",
  },
  {
    id: 9,
    name: "Restaurant Menu",
    thumbnail: "assets/images/restaurant-menu.png",
    preview: "https://alsiam.github.io/web-projects/restaurant-menu",
    code: "https://github.com/alsiam/web-projects/tree/main/restaurant-menu",
  },
  {
    id: 10,
    name: "Football Club",
    thumbnail: "assets/images/football-club.png",
    preview: "https://alsiam.github.io/web-projects/football-club",
    code: "https://github.com/alsiam/web-projects/tree/main/football-club",
  },
  {
    id: 11,
    name: "Katamundi",
    thumbnail: "assets/images/Katamundi.jpg",
    preview: "https://alsiam.github.io/web-projects/restaurant-menu",
    code: "https://github.com/alsiam/web-projects/tree/main/restaurant-menu",
  },
  {
    id: 12,
    name: "Fashion Ecommerce",
    thumbnail: "assets/images/fashion-ecommerce.png",
    preview: "https://alsiam.github.io/web-projects/fashion-ecommerce",
    code: "https://github.com/alsiam/web-projects/tree/main/fashion-ecommerce",
  },
  {
    id: 13,
    name: "Facebook Login",
    thumbnail: "assets/images/facebook-login.png",
    preview: "https://alsiam.github.io/web-projects/facebook-login",
    code: "https://github.com/alsiam/web-projects/tree/main/facebook-login",
  },
  {
    id: 14,
    name: "Personal Website",
    thumbnail: "assets/images/personal-web.png",
    preview: "https://alsiam.github.io/web-projects/personal-website",
    code: "https://github.com/alsiam/web-projects/tree/main/personal-website",
  },
  {
    id: 15,
    name: "Weather Info",
    thumbnail: "assets/images/weather-info.png",
    preview: "https://alsiam.github.io/web-projects/weather-info",
    code: "https://github.com/alsiam/web-projects/tree/main/weather-info",
  },
  {
    id: 16,
    name: "Systematic Page",
    thumbnail: "assets/images/systematic-page.png",
    preview: "https://alsiam.github.io/web-projects/systematic-page",
    code: "https://github.com/alsiam/web-projects/tree/main/systematic-page",
  },
  {
    id: 17,
    name: "Books Library",
    thumbnail: "assets/images/books-library.png",
    preview: "https://alsiam.github.io/web-projects/books-library",
    code: "https://github.com/alsiam/web-projects/tree/main/books-library",
  },
  {
    id: 18,
    name: "Macbook Cart",
    thumbnail: "assets/images/macbook-cart.png",
    preview: "https://alsiam.github.io/web-projects/macbook-cart",
    code: "https://github.com/alsiam/web-projects/tree/main/macbook-cart",
  },
  {
    id: 19,
    name: "Bike Palace",
    thumbnail: "assets/images/bike-palace.png",
    preview: "https://alsiam.github.io/web-projects/bike-palace",
    code: "https://github.com/alsiam/web-projects/tree/main/bike-palace",
  },
  {
    id: 20,
    name: "Youtube UI",
    thumbnail: "assets/images/youtube-ui.png",
    preview: "https://alsiam.github.io/web-projects/youtube-ui",
    code: "https://github.com/alsiam/web-projects/tree/main/youtube-ui",
  },
];
